#!/usr/bin/env python3
"""
Fast Local Repo Cloner for Super Agency Portfolio
Creates missing repos locally with basic structure
"""

import os
import json
import subprocess
from pathlib import Path

def load_portfolio():
    """Load portfolio.json and return repo list"""
    portfolio_path = Path(__file__).parent / "portfolio.json"
    with open(portfolio_path, 'r') as f:
        data = json.load(f)
    return data['repositories']

def get_existing_repos():
    """Get list of already cloned repos"""
    repos_dir = Path(__file__).parent / "repos"
    if not repos_dir.exists():
        repos_dir.mkdir()
        return []

    return [d.name for d in repos_dir.iterdir() if d.is_dir()]

def create_repo_structure(repo_name, visibility, tier, autonomy_level, risk_tier):
    """Create basic repo structure"""
    repo_path = Path(__file__).parent / "repos" / repo_name
    repo_path.mkdir(exist_ok=True)

    # Initialize git repo
    subprocess.run(["git", "init"], cwd=repo_path, check=True, capture_output=True)

    # Create README.md
    readme_content = f"""# {repo_name}

## Super Agency Repository

**Visibility**: {visibility}
**Tier**: {tier}
**Autonomy Level**: {autonomy_level}
**Risk Tier**: {risk_tier}

### Description
TBD - Repository for {repo_name} project in Super Agency portfolio.

### Status
- **Phase**: Initialization
- **Owner**: ResonanceEnergy
- **Created**: 2026-02-20

### Next Steps
1. Define project scope and requirements
2. Set up development environment
3. Implement core functionality
4. Add comprehensive testing
5. Deploy to production

---
*Generated by Super Agency Repo Initializer*
"""

    readme_path = repo_path / "README.md"
    with open(readme_path, 'w') as f:
        f.write(readme_content)

    # Create .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.venv
venv/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
*.tmp
*.temp
"""

    gitignore_path = repo_path / ".gitignore"
    with open(gitignore_path, 'w') as f:
        f.write(gitignore_content)

    # Create basic project structure based on repo name hints
    if any(keyword in repo_name.upper() for keyword in ['AUTO', 'AGENT', 'COUNCIL']):
        # Python agent project
        (repo_path / "src").mkdir()
        (repo_path / "tests").mkdir()
        (repo_path / "docs").mkdir()

        # Create basic __init__.py
        init_path = repo_path / "src" / "__init__.py"
        with open(init_path, 'w') as f:
            f.write(f'"""Super Agency {repo_name} module"""\n')

        # Create basic test file
        test_path = repo_path / "tests" / f"test_{repo_name.lower()}.py"
        with open(test_path, 'w') as f:
            f.write(f'''"""Tests for {repo_name}"""

def test_initialization():
    """Test basic functionality"""
    assert True  # Placeholder test

if __name__ == "__main__":
    test_initialization()
    print("All tests passed!")
''')

    elif any(keyword in repo_name.upper() for keyword in ['TECH', 'PROJECT', 'SYSTEM']):
        # Technology/research project
        (repo_path / "research").mkdir()
        (repo_path / "prototypes").mkdir()
        (repo_path / "docs").mkdir()

    # Initial commit
    subprocess.run(["git", "add", "."], cwd=repo_path, check=True, capture_output=True)
    subprocess.run(["git", "-c", "user.name=Super Agency", "-c", "user.email=agency@resonance.energy", "commit", "-m", "Initial commit - Super Agency repo initialization"], cwd=repo_path, check=True, capture_output=True)

    return repo_path

def main():
    """Main function to create missing repos"""
    print("🔄 Super Agency Fast Repo Cloner")
    print("=" * 40)

    # Load portfolio
    repos = load_portfolio()
    existing = get_existing_repos()

    print(f"📊 Portfolio: {len(repos)} repos")
    print(f"✅ Existing: {len(existing)} repos")
    print(f"🎯 Missing: {len(repos) - len(existing)} repos")
    print()

    missing_repos = []
    for repo in repos:
        if repo['name'] not in existing:
            missing_repos.append(repo)

    if not missing_repos:
        print("✨ All repos already cloned!")
        return

    print("🚀 Creating missing repos...")
    print()

    created_count = 0
    for repo in missing_repos:
        name = repo['name']
        print(f"📁 Creating {name}...")

        try:
            repo_path = create_repo_structure(
                name,
                repo['visibility'],
                repo['tier'],
                repo['autonomy_level'],
                repo['risk_tier']
            )
            print(f"   ✅ Created at {repo_path}")
            created_count += 1
        except Exception as e:
            print(f"   ❌ Failed: {e}")

    print()
    print(f"🎉 Created {created_count} repos successfully!")
    print()
    print("📋 Next steps:")
    print("1. Review created repos in repos/ directory")
    print("2. Customize README.md and project structure as needed")
    print("3. Push to GitHub when ready: git remote add origin <url> && git push -u origin main")
    print("4. Run repo sentry: python agents/orchestrator.py")

if __name__ == "__main__":
    main()