# Super Agency Fast Repo Creator
# Creates all missing repos locally with basic structure

param(
    [string]$PortfolioPath = "portfolio.json",
    [string]$ReposPath = "repos"
)

Write-Host "🔄 Super Agency Fast Repo Creator" -ForegroundColor Cyan
Write-Host "=" * 40 -ForegroundColor Cyan

# Load portfolio
if (!(Test-Path $PortfolioPath)) {
    Write-Error "Portfolio file not found: $PortfolioPath"
    exit 1
}

$portfolio = Get-Content $PortfolioPath | ConvertFrom-Json
$repos = $portfolio.repositories

# Get existing repos
$existingRepos = @()
if (Test-Path $ReposPath) {
    $existingRepos = Get-ChildItem $ReposPath -Directory | Select-Object -ExpandProperty Name
} else {
    New-Item -ItemType Directory -Path $ReposPath -Force | Out-Null
}

Write-Host "📊 Portfolio: $($repos.Count) repos" -ForegroundColor Yellow
Write-Host "✅ Existing: $($existingRepos.Count) repos" -ForegroundColor Green
Write-Host "🎯 Missing: $($repos.Count - $existingRepos.Count) repos" -ForegroundColor Red
Write-Host ""

$missingRepos = $repos | Where-Object { $_.name -notin $existingRepos }

if ($missingRepos.Count -eq 0) {
    Write-Host "✨ All repos already exist!" -ForegroundColor Green
    exit 0
}

Write-Host "🚀 Creating missing repos..." -ForegroundColor Cyan
Write-Host ""

$createdCount = 0

foreach ($repo in $missingRepos) {
    $name = $repo.name
    Write-Host "📁 Creating $name..." -ForegroundColor White

    try {
        $repoPath = Join-Path $ReposPath $name

        # Create directory
        New-Item -ItemType Directory -Path $repoPath -Force | Out-Null

        # Initialize git repo
        Push-Location $repoPath
        git init --quiet

        # Create README.md
        $readmeContent = @"
# $name

## Super Agency Repository

**Visibility**: $($repo.visibility)
**Tier**: $($repo.tier)
**Autonomy Level**: $($repo.autonomy_level)
**Risk Tier**: $($repo.risk_tier)

### Description
TBD - Repository for $name project in Super Agency portfolio.

### Status
- **Phase**: Initialization
- **Owner**: ResonanceEnergy
- **Created**: 2026-02-20

### Next Steps
1. Define project scope and requirements
2. Set up development environment
3. Implement core functionality
4. Add comprehensive testing
5. Deploy to production

---
*Generated by Super Agency Repo Initializer*
"@

        $readmeContent | Out-File -FilePath "README.md" -Encoding UTF8

        # Create .gitignore
        $gitignoreContent = @"
# Python
__pycache__/
*.py[cod]
*`$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.venv
venv/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
*.tmp
*.temp
"@

        $gitignoreContent | Out-File -FilePath ".gitignore" -Encoding UTF8

        # Create basic project structure based on repo name
        if ($name -match "(?i)(auto|agent|council)") {
            # Python agent project
            New-Item -ItemType Directory -Path "src","tests","docs" -Force | Out-Null

            # Create __init__.py
            $initContent = @"
"""Super Agency $name module"""
"@
            $initContent | Out-File -FilePath "src/__init__.py" -Encoding UTF8

            # Create basic test file
            $testContent = @"
"""Tests for $name"""

def test_initialization():
    """Test basic functionality"""
    assert True  # Placeholder test

if __name__ == "__main__":
    test_initialization()
    print("All tests passed!")
"@
            $testContent | Out-File -FilePath "tests/test_$($name.ToLower()).py" -Encoding UTF8
        }
        elseif ($name -match "(?i)(tech|project|system)") {
            # Technology/research project
            New-Item -ItemType Directory -Path "research","prototypes","docs" -Force | Out-Null
        }

        # Initial commit
        git add .
        git -c user.name="Super Agency" -c user.email="agency@resonance.energy" commit -m "Initial commit - Super Agency repo initialization" --quiet

        Pop-Location

        Write-Host "   ✅ Created at $repoPath" -ForegroundColor Green
        $createdCount++
    }
    catch {
        Write-Host "   ❌ Failed: $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "🎉 Created $createdCount repos successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Next steps:" -ForegroundColor Cyan
Write-Host "1. Review created repos in repos/ directory" -ForegroundColor White
Write-Host "2. Customize README.md and project structure as needed" -ForegroundColor White
Write-Host "3. Push to GitHub when ready: git remote add origin <url> && git push -u origin main" -ForegroundColor White
Write-Host "4. Run repo sentry: python agents/orchestrator.py" -ForegroundColor White