"""
Tests for start_ncl.py
Auto-generated by GASKET Test Generator
"""

import pytest
from pathlib import Path
import sys

# Add source to path
sys.path.insert(0, str(Path(__file__).parent.parent))


class TestStartNcl:
    """Test suite for start_ncl"""

    def test_module_imports(self):
        """Test that module can be imported"""
        try:
            import start_ncl
            assert True
        except ImportError:
            pytest.skip("Module not importable in isolation")

    def test_module_has_content(self):
        """Test that source file is not empty"""
        source = Path(__file__).parent.parent / "start_ncl.py"
        if source.exists():
            content = source.read_text()
            assert len(content) > 0
        else:
            pytest.skip("Source file not found")

# Additional tests should be added manually
# or regenerated with AI when ANTHROPIC_API_KEY is set
