#!/usr/bin/env python3
"""
Inner Council Report Generator
Generate detailed reports from council intelligence data
"""

import sys
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
import argparse

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from integrations.ncl_integration import NCLIntegration

def generate_comprehensive_report(days_back: int = 7, output_format: str = "markdown") -> str:
    """Generate comprehensive council intelligence report"""

    ncl_integration = NCLIntegration()

    # Get insights from specified period
    end_date = datetime.now()
    start_date = end_date - timedelta(days=days_back)

    all_insights = ncl_integration.query_council_insights(limit=1000)

    # Filter by date range
    period_insights = []
    for insight in all_insights:
        try:
            insight_date = datetime.fromisoformat(insight.get("timestamp", "").replace("Z", "+00:00"))
            if start_date <= insight_date <= end_date:
                period_insights.append(insight)
        except:
            continue

    # Generate report
    report_data = {
        "report_period": f"{start_date.date()} to {end_date.date()}",
        "total_insights": len(period_insights),
        "analysis_records": len([i for i in period_insights if i.get("type") == "inner_council_analysis"]),
        "daily_reports": len([i for i in period_insights if i.get("type") == "inner_council_daily_report"]),
        "council_members_active": len(set(
            i.get("data", {}).get("council_member") or i.get("data", {}).get("report_date", "")
            for i in period_insights
        )),
        "generated_at": datetime.now().isoformat()
    }

    # Aggregate insights by category
    key_insights = []
    policy_recommendations = []
    strategic_actions = []
    risk_alerts = []

    for insight in period_insights:
        data = insight.get("data", {})

        if insight.get("type") == "inner_council_analysis":
            key_insights.extend(data.get("key_insights", []))
            policy_recommendations.extend(data.get("policy_implications", []))
            strategic_actions.extend(data.get("strategic_recommendations", []))
            risk_alerts.extend(data.get("risk_assessments", []))
        elif insight.get("type") == "inner_council_daily_report":
            key_insights.extend(data.get("summary", {}).get("top_insights", []))
            policy_recommendations.extend(data.get("summary", {}).get("critical_recommendations", []))
            strategic_actions.extend(data.get("summary", {}).get("urgent_actions", []))

    # Remove duplicates and limit
    key_insights = list(set(key_insights))[:20]
    policy_recommendations = list(set(policy_recommendations))[:15]
    strategic_actions = list(set(strategic_actions))[:15]
    risk_alerts = list(set(risk_alerts))[:10]

    # Generate report in requested format
    if output_format == "markdown":
        return generate_markdown_report(report_data, key_insights, policy_recommendations, strategic_actions, risk_alerts)
    elif output_format == "json":
        return generate_json_report(report_data, key_insights, policy_recommendations, strategic_actions, risk_alerts)
    else:
        raise ValueError(f"Unsupported format: {output_format}")

def generate_markdown_report(report_data: Dict, key_insights: List, policy_recommendations: List,
                           strategic_actions: List, risk_alerts: List) -> str:
    """Generate markdown format report"""

    report = f"""# Inner Council Intelligence Report
**Period**: {report_data['report_period']}
**Generated**: {report_data['generated_at']}

## Executive Summary
- **Total Insights**: {report_data['total_insights']}
- **Analysis Records**: {report_data['analysis_records']}
- **Daily Reports**: {report_data['daily_reports']}
- **Active Council Members**: {report_data['council_members_active']}

## Key Insights
{chr(10).join(f"### {i+1}. {insight}" for i, insight in enumerate(key_insights))}

## Policy Recommendations
{chr(10).join(f"### {i+1}. {rec}" for i, rec in enumerate(policy_recommendations))}

## Strategic Actions
{chr(10).join(f"### {i+1}. {action}" for i, action in enumerate(strategic_actions))}

## Risk Alerts
{chr(10).join(f"### {i+1}. {alert}" for i, alert in enumerate(risk_alerts))}

---
*Inner Council Comprehensive Report*
*Generated by Super Agency Intelligence Systems*
"""

    return report

def generate_json_report(report_data: Dict, key_insights: List, policy_recommendations: List,
                        strategic_actions: List, risk_alerts: List) -> str:
    """Generate JSON format report"""

    report = {
        "report_metadata": report_data,
        "key_insights": key_insights,
        "policy_recommendations": policy_recommendations,
        "strategic_actions": strategic_actions,
        "risk_alerts": risk_alerts
    }

    return json.dumps(report, indent=2)

def generate_member_report(member_name: str, days_back: int = 30) -> str:
    """Generate report for specific council member"""

    ncl_integration = NCLIntegration()
    member_insights = ncl_integration.get_council_member_insights(member_name, limit=50)

    # Filter by date
    end_date = datetime.now()
    start_date = end_date - timedelta(days=days_back)

    recent_insights = []
    for insight in member_insights:
        try:
            insight_date = datetime.fromisoformat(insight.get("timestamp", "").replace("Z", "+00:00"))
            if start_date <= insight_date <= end_date:
                recent_insights.append(insight)
        except:
            continue

    report = f"""# Inner Council Member Report: {member_name}
**Period**: Last {days_back} days
**Total Insights**: {len(recent_insights)}

## Recent Activity
"""

    for i, insight in enumerate(recent_insights[:10], 1):
        data = insight.get("data", {})
        report += f"""
### {i}. {data.get('content_title', 'Analysis')}
- **Date**: {insight.get('timestamp', '')[:10]}
- **Type**: {insight.get('type', '')}
"""

        if 'key_insights' in data and data['key_insights']:
            report += f"- **Key Insight**: {data['key_insights'][0]}\n"

    report += f"""
---
*Generated: {datetime.now().isoformat()}*
"""

    return report

def generate_topic_report(topic_keywords: List[str], days_back: int = 7) -> str:
    """Generate report for specific topics"""

    ncl_integration = NCLIntegration()
    topic_insights = ncl_integration.get_topic_insights(topic_keywords, limit=50)

    report = f"""# Inner Council Topic Report
**Topics**: {', '.join(topic_keywords)}
**Period**: Last {days_back} days
**Total Insights**: {len(topic_insights)}

## Topic Analysis
"""

    for i, insight in enumerate(topic_insights[:15], 1):
        data = insight.get("data", {})
        report += f"""
### {i}. {data.get('content_title', 'Analysis')}
- **Member**: {data.get('council_member', 'Unknown')}
- **Date**: {insight.get('timestamp', '')[:10]}
- **Type**: {insight.get('type', '')}
"""

        # Show relevant content
        for field in ['key_insights', 'policy_implications', 'strategic_recommendations']:
            if field in data and data[field]:
                report += f"- **{field.replace('_', ' ').title()}**: {data[field][0]}\n"

    report += f"""
---
*Generated: {datetime.now().isoformat()}*
"""

    return report

def main():
    """CLI interface for report generation"""

    parser = argparse.ArgumentParser(description="Inner Council Report Generator")
    parser.add_argument("--type", choices=["comprehensive", "member", "topic"],
                       default="comprehensive", help="Report type")
    parser.add_argument("--member", help="Council member name (for member reports)")
    parser.add_argument("--topics", nargs="+", help="Topic keywords (for topic reports)")
    parser.add_argument("--days", type=int, default=7, help="Days back to analyze")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown",
                       help="Output format")
    parser.add_argument("--output", help="Output file path")

    args = parser.parse_args()

    try:
        if args.type == "comprehensive":
            report = generate_comprehensive_report(args.days, args.format)
        elif args.type == "member":
            if not args.member:
                print("❌ Member name required for member reports")
                return
            report = generate_member_report(args.member, args.days)
        elif args.type == "topic":
            if not args.topics:
                print("❌ Topic keywords required for topic reports")
                return
            report = generate_topic_report(args.topics, args.days)
        else:
            print("❌ Invalid report type")
            return

        # Output report
        if args.output:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(report)
            print(f"✅ Report saved to: {args.output}")
        else:
            print(report)

    except Exception as e:
        print(f"❌ Error generating report: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()