#!/usr/bin/env python3
"""
NCC Matrix Monitor — Command & Control Health Intelligence System
══════════════════════════════════════════════════════════════════════
Unified monitoring layer that aggregates health data from ALL NCL
subsystems into a single command surface with SLO tracking, alert
routing, dashboard tiles, and historical trend analysis.

Integrates:
    1. System Health   — tools/system_health_check.py (10 checks)
    2. Self-Check      — self_check_protocol.py (8 checks + scoring)
    3. NCC Governance  — pillar_registry + ncc_orchestrator
    4. FPC Intelligence— fpc_integration.scan_fpc_health
    5. Agent Health    — WATCHTOWER / HealthMonitor heartbeats

Architecture:
    ┌─────────────────────────────────────────────────────────┐
    │              NCC MATRIX MONITOR                         │
    │                                                         │
    │  ┌────────────────────────────────────────────────────┐ │
    │  │         MatrixMonitorOrchestrator                   │ │
    │  │  collect_all() → run all collectors → MatrixReport  │ │
    │  └──────────────────┬─────────────────────────────────┘ │
    │                     │                                    │
    │  ┌──────────────────▼─────────────────────────────────┐ │
    │  │            MatrixMonitorStore                       │ │
    │  │  persist snapshots + history (JSON/NDJSON)          │ │
    │  └──────────────────┬─────────────────────────────────┘ │
    │                     │                                    │
    │     ┌───────────────┼───────────────┐                   │
    │     │               │               │                   │
    │  ┌──▼───┐     ┌────▼────┐    ┌────▼─────┐             │
    │  │ SLO  │     │  Alert  │    │  Dash    │              │
    │  │Engine│     │  Router │    │  Tiles   │              │
    │  └──────┘     └─────────┘    └──────────┘              │
    └─────────────────────────────────────────────────────────┘

Doctrine Compliance:
    Art of War: "Know yourself, know your enemy" → continuous deep introspection
    Law 25: "Re-create yourself" → self-healing via corrective alerts
    Habit 1: "Be proactive" → monitor before problems surface
    Dario Amodei: "Interpretability" → every metric explainable
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any, ClassVar

LOG = logging.getLogger("ncc.matrix_monitor")

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent


# ═══════════════════════════════════════════════════════════════
#  Universal Health Check Result
# ═══════════════════════════════════════════════════════════════


class HealthSource(StrEnum):
    """Source subsystem that produced a health check."""

    SYSTEM = "system"
    SELF_CHECK = "self_check"
    NCC_GOVERNANCE = "ncc_governance"
    FPC_INTELLIGENCE = "fpc_intelligence"
    AGENT = "agent"
    ENDPOINT = "endpoint"
    AUTONOMOUS_OPS = "autonomous_ops"
    INTELLIGENCE = "intelligence"
    FORECASTING = "forecasting"
    MEMORY = "memory"
    COMMUNICATION = "communication"
    HELIX_NEWS = "helix_news"


class AlertSeverity(StrEnum):
    """Alert severity levels for the Matrix Monitor."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class HealthCheckResult:
    """Universal health check result — the common protocol all subsystems produce."""

    source: HealthSource
    name: str
    passed: bool
    score: float  # 0.0 to 1.0
    details: str = ""
    recommendation: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["source"] = self.source.value
        return d


@dataclass
class SLODefinition:
    """Service Level Objective definition."""

    name: str
    target: float  # target value (e.g. 0.9 for 90%)
    window_hours: int  # evaluation window
    metric_source: str  # which metric to track
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class SLOStatus:
    """Current SLO evaluation result."""

    slo: SLODefinition
    current_value: float
    budget_remaining: float  # 1.0 = full budget, 0.0 = exhausted
    in_violation: bool
    samples: int
    evaluated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        return d


@dataclass
class AlertRecord:
    """An alert generated by the Matrix Monitor."""

    severity: AlertSeverity
    source: str
    title: str
    details: str
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())
    acknowledged: bool = False

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["severity"] = self.severity.value
        return d


@dataclass
class DashboardTile:
    """Data for a single dashboard tile."""

    tile_type: str  # "progress" | "slo" | "health" | "pillar" | "adoption"
    title: str
    value: Any
    status: str  # "green" | "yellow" | "red" | "grey"
    subtitle: str = ""
    updated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class MatrixReport:
    """Complete Matrix Monitor snapshot."""

    timestamp: str
    overall_score: float
    health_status: str  # EXCELLENT / GOOD / FAIR / DEGRADED / CRITICAL
    checks: list[HealthCheckResult]
    checks_passed: int
    checks_total: int
    slo_statuses: list[SLOStatus]
    slos_in_violation: int
    alerts: list[AlertRecord]
    tiles: list[DashboardTile]
    pillar_summary: dict[str, Any]
    uptime_s: float

    def to_dict(self) -> dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "overall_score": self.overall_score,
            "health_status": self.health_status,
            "checks_passed": self.checks_passed,
            "checks_total": self.checks_total,
            "checks": [c.to_dict() for c in self.checks],
            "slo_statuses": [s.to_dict() for s in self.slo_statuses],
            "slos_in_violation": self.slos_in_violation,
            "alerts": [a.to_dict() for a in self.alerts],
            "tiles": [t.to_dict() for t in self.tiles],
            "pillar_summary": self.pillar_summary,
            "uptime_s": self.uptime_s,
        }


# ═══════════════════════════════════════════════════════════════
#  Matrix Monitor Store — Persistence Layer
# ═══════════════════════════════════════════════════════════════


class MatrixMonitorStore:
    """Persists Matrix Monitor snapshots and provides historical queries.

    Files:
        logs/matrix_latest.json    — most recent snapshot
        logs/matrix_history.ndjson — append-only history for trends
    """

    def __init__(self, log_dir: Path | None = None):
        self._log_dir = log_dir or (_REPO_ROOT / "ncl_agency_runtime" / "logs")
        self._log_dir.mkdir(parents=True, exist_ok=True)
        self._latest_path = self._log_dir / "matrix_latest.json"
        self._history_path = self._log_dir / "matrix_history.ndjson"

    def save(self, report: MatrixReport) -> Path:
        """Persist a MatrixReport snapshot."""
        data = report.to_dict()
        self._latest_path.write_text(
            json.dumps(data, indent=2, default=str) + "\n",
            encoding="utf-8",
        )
        # Append compact entry to history
        compact = {
            "ts": report.timestamp,
            "score": report.overall_score,
            "status": report.health_status,
            "passed": report.checks_passed,
            "total": report.checks_total,
            "slo_violations": report.slos_in_violation,
            "alerts": len(report.alerts),
        }
        with self._history_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(compact) + "\n")
        return self._latest_path

    def get_latest(self) -> dict[str, Any] | None:
        """Load the most recent snapshot."""
        if not self._latest_path.exists():
            return None
        return json.loads(self._latest_path.read_text(encoding="utf-8"))

    def get_history(self, max_entries: int = 100) -> list[dict[str, Any]]:
        """Load recent history entries."""
        if not self._history_path.exists():
            return []
        lines = self._history_path.read_text(encoding="utf-8").splitlines()
        entries = []
        for line in lines[-max_entries:]:
            line = line.strip()
            if line:
                entries.append(json.loads(line))
        return entries

    def get_trend(self, metric: str, max_entries: int = 50) -> list[dict[str, Any]]:
        """Extract a specific metric's trend from history."""
        history = self.get_history(max_entries)
        return [{"ts": h.get("ts", ""), "value": h.get(metric)} for h in history if metric in h]


# ═══════════════════════════════════════════════════════════════
#  SLO Engine
# ═══════════════════════════════════════════════════════════════


class SLOEngine:
    """Service Level Objective engine.

    Evaluates current health metrics against defined SLO targets
    and tracks error budget consumption.
    """

    DEFAULT_SLOS: ClassVar[list[dict[str, Any]]] = [
        {
            "name": "system_health_score",
            "target": 0.8,
            "window_hours": 24,
            "metric_source": "overall_score",
            "description": "Overall system health score must stay above 80%",
        },
        {
            "name": "pillar_availability",
            "target": 0.75,
            "window_hours": 168,
            "metric_source": "pillar_online_ratio",
            "description": "At least 75% of pillars should be online",
        },
        {
            "name": "checks_pass_rate",
            "target": 0.7,
            "window_hours": 24,
            "metric_source": "checks_pass_rate",
            "description": "At least 70% of health checks should pass",
        },
    ]

    def __init__(self, config: dict[str, Any] | None = None):
        self._slos: list[SLODefinition] = []
        self._load_slos(config)

    def _load_slos(self, config: dict[str, Any] | None) -> None:
        """Load SLO definitions from config or defaults."""
        slo_configs = (config or {}).get("slo", {})
        if slo_configs:
            for name, defn in slo_configs.items():
                self._slos.append(
                    SLODefinition(
                        name=name,
                        target=defn.get("target", 0.9),
                        window_hours=defn.get("window_hours", 24),
                        metric_source=defn.get("metric_source", name),
                        description=defn.get("description", ""),
                    )
                )
        else:
            for defn in self.DEFAULT_SLOS:
                self._slos.append(SLODefinition(**defn))

    @property
    def slo_definitions(self) -> list[SLODefinition]:
        return list(self._slos)

    def evaluate(
        self,
        current_metrics: dict[str, float],
        history: list[dict[str, Any]],
    ) -> list[SLOStatus]:
        """Evaluate all SLOs against current metrics and history."""
        results = []
        for slo in self._slos:
            metric_val = current_metrics.get(slo.metric_source, 0.0)
            # Calculate budget from historical values
            window_values = self._extract_window_values(
                history,
                slo.metric_source,
                slo.window_hours,
            )
            if window_values:
                avg_in_window = sum(window_values) / len(window_values)
            else:
                avg_in_window = metric_val

            # Budget: how much of the error budget remains
            # budget = 1.0 when avg == target, 0.0 when avg == 0
            if slo.target > 0:
                budget = min(1.0, max(0.0, avg_in_window / slo.target))
            else:
                budget = 1.0

            in_violation = metric_val < slo.target

            results.append(
                SLOStatus(
                    slo=slo,
                    current_value=round(metric_val, 4),
                    budget_remaining=round(budget, 4),
                    in_violation=in_violation,
                    samples=len(window_values),
                )
            )
        return results

    def _extract_window_values(
        self,
        history: list[dict[str, Any]],
        metric: str,
        window_hours: int,
    ) -> list[float]:
        """Pull metric values from history within the SLO window."""
        now = datetime.now(UTC)
        values = []
        for entry in history:
            ts_str = entry.get("ts", "")
            if not ts_str:
                continue
            try:
                ts = datetime.fromisoformat(ts_str)
                if (now - ts).total_seconds() <= window_hours * 3600:
                    val = entry.get(metric)
                    if val is not None:
                        values.append(float(val))
            except (ValueError, TypeError):
                continue
        return values


# ═══════════════════════════════════════════════════════════════
#  Alert Router
# ═══════════════════════════════════════════════════════════════


class AlertRouter:
    """Generates and routes alerts based on health transitions and SLO violations.

    Doctrine: Law 17 "Suspended terror" — the threat of escalation deters decay.
    """

    def __init__(self) -> None:
        self._alerts: list[AlertRecord] = []
        self._max_alerts = 100

    @property
    def active_alerts(self) -> list[AlertRecord]:
        return [a for a in self._alerts if not a.acknowledged]

    @property
    def all_alerts(self) -> list[AlertRecord]:
        return list(self._alerts)

    def evaluate(
        self,
        checks: list[HealthCheckResult],
        slo_statuses: list[SLOStatus],
        overall_score: float,
    ) -> list[AlertRecord]:
        """Generate alerts from current check results and SLO evaluations."""
        new_alerts: list[AlertRecord] = []

        # Alert on overall score degradation
        if overall_score < 0.3:
            new_alerts.append(
                AlertRecord(
                    severity=AlertSeverity.CRITICAL,
                    source="matrix_monitor",
                    title="System health CRITICAL",
                    details=f"Overall score {overall_score:.2f} is below 0.30 threshold",
                )
            )
        elif overall_score < 0.5:
            new_alerts.append(
                AlertRecord(
                    severity=AlertSeverity.ERROR,
                    source="matrix_monitor",
                    title="System health DEGRADED",
                    details=f"Overall score {overall_score:.2f} is below 0.50 threshold",
                )
            )
        elif overall_score < 0.7:
            new_alerts.append(
                AlertRecord(
                    severity=AlertSeverity.WARNING,
                    source="matrix_monitor",
                    title="System health FAIR",
                    details=f"Overall score {overall_score:.2f} is below 0.70 threshold",
                )
            )

        # Alert on SLO violations
        for slo_status in slo_statuses:
            if slo_status.in_violation:
                severity = AlertSeverity.ERROR
                if slo_status.budget_remaining < 0.2:
                    severity = AlertSeverity.CRITICAL
                elif slo_status.budget_remaining < 0.5:
                    severity = AlertSeverity.ERROR
                else:
                    severity = AlertSeverity.WARNING

                new_alerts.append(
                    AlertRecord(
                        severity=severity,
                        source="slo_engine",
                        title=f"SLO violation: {slo_status.slo.name}",
                        details=(
                            f"Current: {slo_status.current_value:.2f}, "
                            f"Target: {slo_status.slo.target:.2f}, "
                            f"Budget remaining: {slo_status.budget_remaining:.1%}"
                        ),
                    )
                )

        # Alert on critical check failures
        for check in checks:
            if not check.passed and check.score == 0.0:
                new_alerts.append(
                    AlertRecord(
                        severity=AlertSeverity.ERROR,
                        source=check.source.value,
                        title=f"Check failed: {check.name}",
                        details=check.details,
                    )
                )

        # Store and trim
        self._alerts.extend(new_alerts)
        if len(self._alerts) > self._max_alerts:
            self._alerts = self._alerts[-self._max_alerts :]

        return new_alerts

    def acknowledge(self, index: int) -> bool:
        """Acknowledge an alert by index."""
        if 0 <= index < len(self._alerts):
            self._alerts[index].acknowledged = True
            return True
        return False

    def clear_acknowledged(self) -> int:
        """Remove acknowledged alerts."""
        before = len(self._alerts)
        self._alerts = [a for a in self._alerts if not a.acknowledged]
        return before - len(self._alerts)


# ═══════════════════════════════════════════════════════════════
#  Health Data Collectors — Adapters for each subsystem
# ═══════════════════════════════════════════════════════════════


def _collect_system_health(repo_root: Path) -> list[HealthCheckResult]:
    """Collect health checks from tools/system_health_check.py — adapted to HealthCheckResult."""
    results: list[HealthCheckResult] = []
    try:
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "system_health_check",
            str(repo_root / "tools" / "system_health_check.py"),
        )
        if spec and spec.loader:
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            checker = mod.NCLHealthChecker(str(repo_root / "ncl_config.json"))

            # Run non-network checks only (avoid HTTP timeouts)
            safe_checks = [
                ("python_deps", checker.check_python_dependencies),
                ("directory_structure", checker.check_directory_structure),
                ("schemas", checker.check_schemas),
                ("golden_tasks", checker.check_golden_tasks),
                ("shortcuts_pack", checker.check_shortcuts_pack),
                ("agency_runtime", checker.check_agency_runtime),
                ("onedrop_setup", checker.check_onedrop_setup),
            ]

            for name, check_fn in safe_checks:
                try:
                    passed = check_fn()
                    detail = json.dumps(checker.results.get(name, {}))
                    results.append(
                        HealthCheckResult(
                            source=HealthSource.SYSTEM,
                            name=name,
                            passed=passed,
                            score=1.0 if passed else 0.0,
                            details=detail,
                        )
                    )
                except Exception as exc:
                    results.append(
                        HealthCheckResult(
                            source=HealthSource.SYSTEM,
                            name=name,
                            passed=False,
                            score=0.0,
                            details=f"Check error: {exc}",
                        )
                    )
    except Exception as exc:
        LOG.warning("System health collector failed: %s", exc)
        results.append(
            HealthCheckResult(
                source=HealthSource.SYSTEM,
                name="system_health_collector",
                passed=False,
                score=0.0,
                details=f"Collector failed: {exc}",
            )
        )
    return results


def _collect_self_check(repo_root: Path) -> list[HealthCheckResult]:
    """Collect health checks from self_check_protocol.py — adapted to HealthCheckResult."""
    results: list[HealthCheckResult] = []
    try:
        from ncl_agency_runtime.runtime.self_check_protocol import (
            SelfCheckProtocol,
        )

        protocol = SelfCheckProtocol(repo_root=repo_root)
        report = protocol.run_all()
        for check in report.get("results", []):
            results.append(
                HealthCheckResult(
                    source=HealthSource.SELF_CHECK,
                    name=check["name"],
                    passed=check["passed"],
                    score=check["score"],
                    details=check.get("details", ""),
                    recommendation=check.get("recommendation", ""),
                )
            )
    except Exception as exc:
        LOG.warning("Self-check collector failed: %s", exc)
        results.append(
            HealthCheckResult(
                source=HealthSource.SELF_CHECK,
                name="self_check_collector",
                passed=False,
                score=0.0,
                details=f"Collector failed: {exc}",
            )
        )
    return results


def _collect_ncc_governance(repo_root: Path) -> tuple[list[HealthCheckResult], dict[str, Any]]:
    """Collect health from PillarRegistry and return pillar summary."""
    results: list[HealthCheckResult] = []
    pillar_summary: dict[str, Any] = {}
    try:
        from ncl_agency_runtime.runtime.pillar_registry import (
            PillarRegistry,
            bootstrap_registry,
        )

        registry = PillarRegistry.get_instance()
        # Bootstrap if empty
        if not registry.list_pillars():
            bootstrap_registry()

        # Promote bootstrapping pillars to online via heartbeat —
        # the Matrix Monitor confirming their presence IS the heartbeat.
        for pillar in registry.list_pillars():
            registry.heartbeat(pillar.pillar_id)

        summary = registry.health_summary()
        pillar_summary = summary

        total = summary.get("total_pillars", 0)
        online = summary.get("online", 0)
        degraded = summary.get("degraded", 0)

        # Overall pillar health check
        if total > 0:
            online_ratio = online / total
        else:
            online_ratio = 0.0

        results.append(
            HealthCheckResult(
                source=HealthSource.NCC_GOVERNANCE,
                name="pillar_availability",
                passed=online_ratio >= 0.5,
                score=online_ratio,
                details=f"{online}/{total} pillars online, {degraded} degraded",
            )
        )

        # Triad check
        triad_online = registry.triad_online()
        results.append(
            HealthCheckResult(
                source=HealthSource.NCC_GOVERNANCE,
                name="triad_online",
                passed=triad_online,
                score=1.0 if triad_online else 0.0,
                details=f"Triad status: {registry.triad_status()}",
                recommendation="" if triad_online else "Bring offline triad pillars online",
            )
        )

        # Per-pillar checks
        for pid, info in summary.get("pillars", {}).items():
            status = info.get("status", "offline")
            is_online = status in ("online", "bootstrapping")
            results.append(
                HealthCheckResult(
                    source=HealthSource.NCC_GOVERNANCE,
                    name=f"pillar_{pid}",
                    passed=is_online,
                    score=1.0 if status == "online" else (0.5 if status in ("degraded", "bootstrapping") else 0.0),
                    details=f"{info.get('name', pid)}: {status} ({info.get('capabilities', 0)} capabilities)",
                )
            )

    except Exception as exc:
        LOG.warning("NCC governance collector failed: %s", exc)
        results.append(
            HealthCheckResult(
                source=HealthSource.NCC_GOVERNANCE,
                name="governance_collector",
                passed=False,
                score=0.0,
                details=f"Collector failed: {exc}",
            )
        )
    return results, pillar_summary


def _collect_fpc_health(repo_root: Path) -> list[HealthCheckResult]:
    """Collect health checks from FPC intelligence scanner."""
    results: list[HealthCheckResult] = []
    try:
        from ncl_agency_runtime.runtime.fpc_integration import scan_fpc_health

        gaps = scan_fpc_health(repo_root)
        if not gaps:
            results.append(
                HealthCheckResult(
                    source=HealthSource.FPC_INTELLIGENCE,
                    name="fpc_health",
                    passed=True,
                    score=1.0,
                    details="FPC intelligence layer healthy — no gaps detected",
                )
            )
        else:
            # Convert gaps to individual check results
            high_severity = sum(1 for g in gaps if g.get("severity") == "high")
            score = max(0.0, 1.0 - (high_severity * 0.2) - ((len(gaps) - high_severity) * 0.05))
            results.append(
                HealthCheckResult(
                    source=HealthSource.FPC_INTELLIGENCE,
                    name="fpc_health",
                    passed=high_severity == 0,
                    score=round(score, 2),
                    details=f"{len(gaps)} gaps detected ({high_severity} high severity)",
                    recommendation="Review FPC intelligence gaps",
                )
            )
            for gap in gaps[:5]:  # Top 5 gaps as individual checks
                results.append(
                    HealthCheckResult(
                        source=HealthSource.FPC_INTELLIGENCE,
                        name=f"fpc_gap_{gap.get('category', 'unknown')}",
                        passed=False,
                        score=0.3 if gap.get("severity") == "medium" else 0.0,
                        details=gap.get("description", ""),
                    )
                )
    except Exception as exc:
        LOG.warning("FPC health collector failed: %s", exc)
        results.append(
            HealthCheckResult(
                source=HealthSource.FPC_INTELLIGENCE,
                name="fpc_collector",
                passed=False,
                score=0.0,
                details=f"Collector failed: {exc}",
            )
        )
    return results


def _collect_daily_briefs(repo_root: Path) -> tuple[list[HealthCheckResult], dict[str, Any]]:
    """Collect daily brief status — checks freshness and availability of AZ + C-Suite briefs."""
    results: list[HealthCheckResult] = []
    brief_summary: dict[str, Any] = {"az": {}, "csuite": {}}
    briefs_root = repo_root / "reports" / "daily_briefs"

    for brief_type, label in [("az", "AZ PRIME Brief"), ("csuite", "C-Suite Brief")]:
        brief_dir = briefs_root / brief_type
        if not brief_dir.exists():
            results.append(
                HealthCheckResult(
                    source=HealthSource.FPC_INTELLIGENCE,
                    name=f"brief_{brief_type}",
                    passed=False,
                    score=0.0,
                    details=f"{label}: no output directory",
                    recommendation=f"Run {label} to generate first report",
                )
            )
            brief_summary[brief_type] = {"status": "missing", "latest": None}
            continue

        # Find latest timestamped folder
        folders = sorted(
            [d for d in brief_dir.iterdir() if d.is_dir()],
            key=lambda d: d.name,
            reverse=True,
        )
        if not folders:
            results.append(
                HealthCheckResult(
                    source=HealthSource.FPC_INTELLIGENCE,
                    name=f"brief_{brief_type}",
                    passed=False,
                    score=0.0,
                    details=f"{label}: directory exists but no reports generated",
                    recommendation=f"Run {label}.save() to generate a report",
                )
            )
            brief_summary[brief_type] = {"status": "empty", "latest": None}
            continue

        latest = folders[0]
        md_files = list(latest.glob("*.md"))
        pdf_files = list(latest.glob("*.pdf"))
        has_md = len(md_files) > 0
        has_pdf = len(pdf_files) > 0

        # Check freshness — parse YYYYMMDD_HHMMSS from folder name
        try:
            ts = datetime.strptime(latest.name, "%Y%m%d_%H%M%S")
            age_hours = (datetime.now() - ts).total_seconds() / 3600
            fresh = age_hours < 24
        except ValueError:
            age_hours = -1
            fresh = False

        score = 0.0
        if has_md and has_pdf:
            score = 1.0 if fresh else 0.5
        elif has_md:
            score = 0.7 if fresh else 0.3

        if fresh and has_md:
            detail = f"{label}: current ({age_hours:.1f}h ago)"
            if has_pdf:
                detail += " [MD+PDF]"
            else:
                detail += " [MD only]"
        elif has_md:
            detail = f"{label}: stale ({age_hours:.1f}h ago)"
        else:
            detail = f"{label}: folder exists but no output files"

        results.append(
            HealthCheckResult(
                source=HealthSource.FPC_INTELLIGENCE,
                name=f"brief_{brief_type}",
                passed=fresh and has_md,
                score=score,
                details=detail,
                recommendation="" if (fresh and has_md) else f"Regenerate {label}",
            )
        )

        brief_summary[brief_type] = {
            "status": "current" if fresh else "stale",
            "latest_dir": str(latest),
            "md": str(md_files[0]) if md_files else None,
            "pdf": str(pdf_files[0]) if pdf_files else None,
            "age_hours": round(age_hours, 1),
            "timestamp": latest.name,
        }

    return results, brief_summary


# ═══════════════════════════════════════════════════════════════
#  Extended Collectors — Autonomous Ops, Intelligence, Forecasting, Memory, Comms
# ═══════════════════════════════════════════════════════════════


def _collect_autonomous_ops(repo_root: Path) -> list[HealthCheckResult]:
    """Check autonomous daemon state, mission queue, and digital labour pool."""
    results: list[HealthCheckResult] = []

    # ── Mission queue depth ────────────────────────────────────
    missions_dir = repo_root / "ncl_agency_runtime" / "missions"
    try:
        if missions_dir.exists():
            pending = list(missions_dir.glob("*.json"))
            queue_ok = len(pending) < 50  # alert if backlog > 50
            results.append(
                HealthCheckResult(
                    source=HealthSource.AUTONOMOUS_OPS,
                    name="mission_queue",
                    passed=queue_ok,
                    score=1.0 if len(pending) == 0 else max(0.3, 1.0 - len(pending) / 100),
                    details=f"{len(pending)} missions queued",
                    recommendation="" if queue_ok else "Process mission backlog",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.AUTONOMOUS_OPS,
                    name="mission_queue",
                    passed=False,
                    score=0.0,
                    details="Mission queue directory not found",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.AUTONOMOUS_OPS,
                name="mission_queue",
                passed=False,
                score=0.0,
                details=f"Check error: {exc}",
            )
        )

    # ── Daemon journal freshness ───────────────────────────────
    journal_path = repo_root / "ncl_agency_runtime" / "logs" / "daemon_journal.ndjson"
    try:
        if journal_path.exists():
            mtime = journal_path.stat().st_mtime
            age_hours = (time.time() - mtime) / 3600
            fresh = age_hours < 6
            results.append(
                HealthCheckResult(
                    source=HealthSource.AUTONOMOUS_OPS,
                    name="daemon_journal",
                    passed=fresh,
                    score=1.0 if age_hours < 1 else (0.7 if age_hours < 6 else 0.3),
                    details=f"Journal last updated {age_hours:.1f}h ago",
                    recommendation="" if fresh else "Daemon may be idle — check autonomous_daemon.py",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.AUTONOMOUS_OPS,
                    name="daemon_journal",
                    passed=False,
                    score=0.0,
                    details="Daemon journal not found — daemon has never run",
                    recommendation="Start autonomous daemon",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.AUTONOMOUS_OPS,
                name="daemon_journal",
                passed=False,
                score=0.0,
                details=f"Check error: {exc}",
            )
        )

    # ── Digital Labour Pool importability ─────────────────────
    try:
        from ncl_agency_runtime.runtime.digital_labour import DigitalLabourPool

        pool = DigitalLabourPool.get_instance()
        stats = pool.stats
        results.append(
            HealthCheckResult(
                source=HealthSource.AUTONOMOUS_OPS,
                name="labour_pool",
                passed=True,
                score=1.0,
                details=(
                    f"max_workers={stats.get('max_workers', '?')} "
                    f"queue={stats.get('queue_size', 0)} "
                    f"completed={stats.get('completed', 0)} "
                    f"failed={stats.get('failed', 0)}"
                ),
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.AUTONOMOUS_OPS,
                name="labour_pool",
                passed=False,
                score=0.0,
                details=f"DigitalLabourPool unavailable: {exc}",
            )
        )

    # ── Dead-letter mission count ──────────────────────────────
    dead_letter_dir = repo_root / "ncl_agency_runtime" / "missions" / "dead_letters"
    try:
        if dead_letter_dir.exists():
            dl_count = len(list(dead_letter_dir.glob("*.json")))
            results.append(
                HealthCheckResult(
                    source=HealthSource.AUTONOMOUS_OPS,
                    name="mission_dead_letters",
                    passed=dl_count == 0,
                    score=1.0 if dl_count == 0 else max(0.0, 1.0 - dl_count * 0.1),
                    details=f"{dl_count} dead-letter missions",
                    recommendation="" if dl_count == 0 else "Review dead-letter missions for errors",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.AUTONOMOUS_OPS,
                name="mission_dead_letters",
                passed=False,
                score=0.0,
                details=f"Check error: {exc}",
            )
        )

    return results


def _collect_intelligence_health(repo_root: Path) -> list[HealthCheckResult]:
    """Check intelligence engine registrations, scraper, and data pipeline."""
    results: list[HealthCheckResult] = []

    # ── Intelligence engine importability ────────────────────
    engines = [
        ("youtube_intelligence", "ncl_agency_runtime.fpc.youtube_intelligence", "YouTubeIntelligenceEngine"),
        ("x_intelligence", "ncl_agency_runtime.fpc.x_intelligence", "XIntelligenceEngine"),
        ("github_intelligence", "ncl_agency_runtime.fpc.github_intelligence", "GitHubIntelligence"),
        ("reddit_intelligence", "ncl_agency_runtime.fpc.reddit_intelligence", "RedditIntelligence"),
        ("substack_intelligence", "ncl_agency_runtime.fpc.substack_intelligence", "SubstackIntelligence"),
        ("google_trends_intelligence", "ncl_agency_runtime.fpc.google_trends_intelligence", "GoogleTrendsIntelligence"),
        ("tiktok_intelligence", "ncl_agency_runtime.fpc.tiktok_intelligence", "TikTokIntelligence"),
        ("instagram_intelligence", "ncl_agency_runtime.fpc.instagram_intelligence", "InstagramIntelligence"),
        ("ai_upload_intelligence", "ncl_agency_runtime.fpc.ai_upload_intelligence", "AIUploadEngine"),
    ]
    import importlib

    online_count = 0
    for name, module_path, class_name in engines:
        try:
            mod = importlib.import_module(module_path)
            getattr(mod, class_name)
            online_count += 1
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name=f"engine_{name}",
                    passed=True,
                    score=1.0,
                    details=f"{class_name} importable",
                )
            )
        except Exception as exc:
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name=f"engine_{name}",
                    passed=False,
                    score=0.0,
                    details=f"{class_name} unavailable: {exc}",
                    recommendation=f"Check ncl_agency_runtime/fpc/{name}.py",
                )
            )

    # ── Scraper importability ─────────────────────────────────
    try:
        from ncl_agency_runtime.fpc.scraper import TopicScraper  # type: ignore[import]

        TopicScraper  # noqa: B018 — verify importability
        results.append(
            HealthCheckResult(
                source=HealthSource.INTELLIGENCE,
                name="scraper",
                passed=True,
                score=1.0,
                details="TopicScraper importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.INTELLIGENCE,
                name="scraper",
                passed=False,
                score=0.0,
                details=f"Scraper unavailable: {exc}",
            )
        )

    # ── Topics registry freshness ─────────────────────────────
    topics_path = repo_root / "_config" / "topics_registry.json"
    try:
        if topics_path.exists():
            import json as _json

            with open(topics_path, encoding="utf-8") as f:
                registry = _json.load(f)
            topic_count = len(registry) if isinstance(registry, (list, dict)) else 0
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name="topics_registry",
                    passed=topic_count > 0,
                    score=1.0 if topic_count > 10 else 0.5,
                    details=f"{topic_count} topics registered",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name="topics_registry",
                    passed=False,
                    score=0.0,
                    details="Topics registry not found",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.INTELLIGENCE,
                name="topics_registry",
                passed=False,
                score=0.0,
                details=f"Registry load error: {exc}",
            )
        )

    # ── Event log data freshness ──────────────────────────────
    event_log = repo_root / "data" / "youtube_digest.ndjson"
    try:
        if event_log.exists():
            mtime = event_log.stat().st_mtime
            age_hours = (time.time() - mtime) / 3600
            fresh = age_hours < 48
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name="event_log_freshness",
                    passed=fresh,
                    score=1.0 if age_hours < 12 else (0.6 if age_hours < 48 else 0.2),
                    details=f"Event log last updated {age_hours:.1f}h ago",
                    recommendation="" if fresh else "Run data pipeline to refresh event log",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.INTELLIGENCE,
                    name="event_log_freshness",
                    passed=False,
                    score=0.0,
                    details="Event log not found",
                    recommendation="Run data ingestion pipeline",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.INTELLIGENCE,
                name="event_log_freshness",
                passed=False,
                score=0.0,
                details=f"Check error: {exc}",
            )
        )

    return results


def _collect_forecasting_health(repo_root: Path) -> list[HealthCheckResult]:
    """Check FPC forecasting subsystems: scheduler, signal scorer, persistence, council."""
    results: list[HealthCheckResult] = []

    # ── Scheduler importability ────────────────────────────────
    try:
        from ncl_agency_runtime.fpc.scheduler import Scheduler

        sched = Scheduler()
        tasks = sched.list_tasks()
        enabled = [t for t in tasks if t.get("enabled", False)]
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="fpc_scheduler",
                passed=True,
                score=1.0 if enabled else 0.5,
                details=f"{len(tasks)} tasks configured, {len(enabled)} enabled",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="fpc_scheduler",
                passed=False,
                score=0.0,
                details=f"Scheduler unavailable: {exc}",
            )
        )

    # ── Signal scorer importability ────────────────────────────
    try:
        from ncl_agency_runtime.fpc.signal_scorer import SignalScorer

        scorer = SignalScorer()
        domain_h = scorer.domain_health()
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="signal_scorer",
                passed=True,
                score=1.0,
                details=f"{len(domain_h)} domains tracked",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="signal_scorer",
                passed=False,
                score=0.0,
                details=f"SignalScorer unavailable: {exc}",
            )
        )

    # ── Persistence / SQLite store ─────────────────────────────
    try:
        from ncl_agency_runtime.fpc.persistence import PredictionStore  # type: ignore[import]

        PredictionStore()
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="fpc_persistence",
                passed=True,
                score=1.0,
                details="FPC persistence store accessible",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="fpc_persistence",
                passed=False,
                score=0.0,
                details=f"PredictionStore unavailable: {exc}",
            )
        )

    # ── Council orchestrator ───────────────────────────────────
    try:
        from ncl_agency_runtime.fpc.agents.orchestrator import MissionControl  # type: ignore[import]

        MissionControl  # noqa: B018 — verify importability
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="council_orchestrator",
                passed=True,
                score=1.0,
                details="MissionControl (FPC orchestrator) importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="council_orchestrator",
                passed=False,
                score=0.0,
                details=f"MissionControl unavailable: {exc}",
            )
        )

    # ── Prediction tracker data freshness ─────────────────────
    tracker_path = repo_root / "state" / "predictions.json"
    try:
        if tracker_path.exists():
            mtime = tracker_path.stat().st_mtime
            age_hours = (time.time() - mtime) / 3600
            fresh = age_hours < 24
            import json as _json

            with open(tracker_path, encoding="utf-8") as f:
                preds = _json.load(f)
            pred_count = len(preds) if isinstance(preds, list) else 0
            results.append(
                HealthCheckResult(
                    source=HealthSource.FORECASTING,
                    name="prediction_tracker",
                    passed=fresh,
                    score=1.0 if age_hours < 6 else (0.6 if fresh else 0.2),
                    details=f"{pred_count} predictions stored, updated {age_hours:.1f}h ago",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.FORECASTING,
                    name="prediction_tracker",
                    passed=False,
                    score=0.0,
                    details="Predictions file not found — no forecasts yet",
                    recommendation="Run FPC council to generate first predictions",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.FORECASTING,
                name="prediction_tracker",
                passed=False,
                score=0.0,
                details=f"Check error: {exc}",
            )
        )

    return results


def _collect_memory_health(repo_root: Path) -> list[HealthCheckResult]:
    """Check memory subsystems: MemoryAPI stats, second brain, 3-tier stores."""
    results: list[HealthCheckResult] = []

    # ── MemoryAPI stats ────────────────────────────────────────
    try:
        from ncl_agency_runtime.runtime.memory_api import MemoryAPI

        api = MemoryAPI()
        stats = api.get_memory_stats()
        total = sum(v for v in stats.values() if isinstance(v, int))
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="memory_api",
                passed=True,
                score=1.0,
                details=f"MemoryAPI operational — {total} total memory entries: {stats}",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="memory_api",
                passed=False,
                score=0.0,
                details=f"MemoryAPI unavailable: {exc}",
            )
        )

    # ── Memory manager / 3-tier ───────────────────────────────
    try:
        from ncl_agency_runtime.runtime.memory_manager import MemoryManagerCLI  # type: ignore[import]

        MemoryManagerCLI  # noqa: B018 — verify importability
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="memory_manager",
                passed=True,
                score=1.0,
                details="MemoryManagerCLI importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="memory_manager",
                passed=False,
                score=0.0,
                details=f"MemoryManagerCLI unavailable: {exc}",
            )
        )

    # ── Second brain file ─────────────────────────────────────
    try:
        from ncl_agency_runtime.fpc.second_brain import SecondBrainEngine  # type: ignore[import]

        SecondBrainEngine  # noqa: B018 — verify importability
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="second_brain",
                passed=True,
                score=1.0,
                details="SecondBrainEngine importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name="second_brain",
                passed=False,
                score=0.0,
                details=f"SecondBrainEngine unavailable: {exc}",
            )
        )

    # ── Memory file stores existence ──────────────────────────
    memory_paths = [
        ("ncl_memory", repo_root / "fractal_future" / "ncl_memory"),
        ("state_dir", repo_root / "state"),
        ("data_dir", repo_root / "data"),
    ]
    for label, path in memory_paths:
        exists = path.exists()
        results.append(
            HealthCheckResult(
                source=HealthSource.MEMORY,
                name=f"store_{label}",
                passed=exists,
                score=1.0 if exists else 0.0,
                details=f"{path.name}: {'exists' if exists else 'missing'}",
            )
        )

    return results


def _collect_communication_health(repo_root: Path) -> list[HealthCheckResult]:
    """Check communication layer: inter-pillar bus, relay server, Telegram bot."""
    results: list[HealthCheckResult] = []

    # ── Inter-pillar bus stats ─────────────────────────────────
    try:
        from ncl_agency_runtime.runtime.inter_pillar_bus import InterPillarBus

        bus = InterPillarBus.get_instance()
        stats = bus.stats
        dead = len(bus.dead_letters)
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="inter_pillar_bus",
                passed=dead == 0,
                score=1.0 if dead == 0 else max(0.3, 1.0 - dead * 0.1),
                details=(
                    f"published={stats.get('published', 0)} delivered={stats.get('delivered', 0)} dead_letters={dead}"
                ),
                recommendation="" if dead == 0 else f"{dead} dead-letter messages — check bus subscriptions",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="inter_pillar_bus",
                passed=False,
                score=0.0,
                details=f"InterPillarBus unavailable: {exc}",
            )
        )

    # ── Relay server process check (port 8787) ─────────────────
    try:
        import socket

        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(0.5)
        result = sock.connect_ex(("127.0.0.1", 8787))
        sock.close()
        relay_up = result == 0
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="relay_server",
                passed=relay_up,
                score=1.0 if relay_up else 0.0,
                details="Relay server responding on :8787" if relay_up else "Relay server :8787 not reachable",
                recommendation="" if relay_up else "Start relay_server.py",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="relay_server",
                passed=False,
                score=0.0,
                details=f"Port check error: {exc}",
            )
        )

    # ── Telegram bot runner importability ─────────────────────
    bot_script = repo_root / "run_telegram_bot.py"
    results.append(
        HealthCheckResult(
            source=HealthSource.COMMUNICATION,
            name="telegram_bot_script",
            passed=bot_script.exists(),
            score=1.0 if bot_script.exists() else 0.0,
            details="run_telegram_bot.py present" if bot_script.exists() else "run_telegram_bot.py missing",
        )
    )

    # ── Learning engine importability ─────────────────────────
    try:
        from ncl_agency_runtime.runtime.learning_engine import LearningEngine  # type: ignore[import]

        LearningEngine  # noqa: B018 — verify importability
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="learning_engine",
                passed=True,
                score=1.0,
                details="LearningEngine importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.COMMUNICATION,
                name="learning_engine",
                passed=False,
                score=0.0,
                details=f"LearningEngine unavailable: {exc}",
            )
        )

    return results


# ═══════════════════════════════════════════════════════════════
#  HELIX News — Clip Cache & Episode Health
# ═══════════════════════════════════════════════════════════════


def _collect_helix_news(repo_root: Path) -> list[HealthCheckResult]:
    """Check HELIX News clip cache and episode freshness."""
    results: list[HealthCheckResult] = []

    # ── Clip cache health ──────────────────────────────────────
    cache_dir = repo_root / "state" / "helix_clip_cache"
    manifest_path = cache_dir / "manifest.json"
    try:
        if manifest_path.exists():
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            total = len(manifest)
            # Count fresh clips (file exists + age < 24h)
            fresh_count = 0
            for entry in manifest.values():
                video = entry.get("video", "")
                rendered_at = entry.get("rendered_at", "")
                if not video or not Path(video).exists():
                    continue
                try:
                    ts = datetime.fromisoformat(rendered_at)
                    age_h = (datetime.now() - ts).total_seconds() / 3600
                    if age_h < 24:
                        fresh_count += 1
                except (ValueError, TypeError):
                    pass
            stale_count = total - fresh_count
            score = fresh_count / max(total, 1) if total > 0 else 0.5
            results.append(
                HealthCheckResult(
                    source=HealthSource.HELIX_NEWS,
                    name="helix_clip_cache",
                    passed=True,
                    score=round(min(1.0, score), 2),
                    details=f"{fresh_count} fresh / {total} total clips ({stale_count} stale)"
                    if total > 0
                    else "Cache initialised, awaiting first prerender cycle",
                    recommendation="" if fresh_count > 0 else "Run 'helix_prerender' to populate clip cache",
                )
            )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.HELIX_NEWS,
                    name="helix_clip_cache",
                    passed=False,
                    score=0.0,
                    details="Clip cache manifest not found",
                    recommendation="Run IncrementalRenderer to initialise the clip cache",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_clip_cache",
                passed=False,
                score=0.0,
                details=f"Cache check error: {exc}",
            )
        )

    # ── Latest episode freshness ───────────────────────────────
    episodes_dir = repo_root / "reports" / "helix_news"
    _TS_RE = re.compile(r"(\d{8}_\d{6})")
    try:
        if episodes_dir.exists():
            # Find folders that actually contain episode.mp4
            ep_folders = [d for d in episodes_dir.iterdir() if d.is_dir() and (d / "episode.mp4").exists()]
            if ep_folders:
                # Sort by embedded timestamp (most recent first)
                def _extract_ts(d: Path) -> str:
                    m = _TS_RE.search(d.name)
                    return m.group(1) if m else "00000000_000000"

                ep_folders.sort(key=_extract_ts, reverse=True)
                latest = ep_folders[0]
                # Parse timestamp from folder name via regex
                ts_match = _TS_RE.search(latest.name)
                if ts_match:
                    try:
                        ts = datetime.strptime(ts_match.group(1), "%Y%m%d_%H%M%S")
                        age_hours = (datetime.now() - ts).total_seconds() / 3600
                    except ValueError:
                        age_hours = -1.0
                else:
                    age_hours = -1.0
                fresh = 0 < age_hours < 24
                score = 1.0 if fresh else 0.5
                results.append(
                    HealthCheckResult(
                        source=HealthSource.HELIX_NEWS,
                        name="helix_latest_episode",
                        passed=fresh,
                        score=score,
                        details=(f"Latest: {latest.name} ({age_hours:.1f}h ago)" + " [episode.mp4]"),
                        recommendation="" if fresh else "Run BriefAssembler.assemble() to produce episode",
                    )
                )
            else:
                # Folders exist but none contain episode.mp4
                all_folders = [d for d in episodes_dir.iterdir() if d.is_dir()]
                results.append(
                    HealthCheckResult(
                        source=HealthSource.HELIX_NEWS,
                        name="helix_latest_episode",
                        passed=False,
                        score=0.2,
                        details=f"{len(all_folders)} output folders but none contain episode.mp4",
                        recommendation="Run HELIX pipeline to generate episode",
                    )
                )
        else:
            results.append(
                HealthCheckResult(
                    source=HealthSource.HELIX_NEWS,
                    name="helix_latest_episode",
                    passed=False,
                    score=0.0,
                    details="HELIX output directory reports/helix_news/ not found",
                    recommendation="Run HELIX pipeline at least once",
                )
            )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_latest_episode",
                passed=False,
                score=0.0,
                details=f"Episode check error: {exc}",
            )
        )

    # ── Pipeline module importability ──────────────────────────
    try:
        from ncl_agency_runtime.fpc.helix_news.clip_cache import (
            BriefAssembler,
            ClipCache,
            IncrementalRenderer,
        )

        # Verify classes are callable
        ClipCache, IncrementalRenderer, BriefAssembler  # noqa: B018
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_pipeline_modules",
                passed=True,
                score=1.0,
                details="ClipCache, IncrementalRenderer, BriefAssembler importable",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_pipeline_modules",
                passed=False,
                score=0.0,
                details=f"HELIX pipeline import failed: {exc}",
                recommendation="Check clip_cache.py for syntax or dependency errors",
            )
        )

    # ── Daemon schedule wiring ─────────────────────────────────
    try:
        from unittest.mock import patch as _patch

        from ncl_agency_runtime.runtime.autonomous_daemon import TaskGenerator

        gen = TaskGenerator.__new__(TaskGenerator)
        gen.repo_root = repo_root
        has_prerender = False
        has_assemble = False
        # Probe target hours by mocking datetime.now(UTC) inside the method
        for hour in (8, 12, 16, 18):
            fake_now = datetime(2026, 1, 15, hour, 0, 0, tzinfo=UTC)
            with _patch(
                "ncl_agency_runtime.runtime.autonomous_daemon.datetime",
            ) as mock_dt:
                mock_dt.now.return_value = fake_now
                mock_dt.side_effect = lambda *a, **kw: datetime(*a, **kw)
                tasks = gen.generate_scheduled_tasks()
            for t in tasks:
                cat = getattr(t, "category", "")
                if cat == "helix_prerender":
                    has_prerender = True
                elif cat == "helix_assemble":
                    has_assemble = True
        wired = has_prerender and has_assemble
        parts = []
        if has_prerender:
            parts.append("prerender")
        if has_assemble:
            parts.append("assemble")
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_daemon_schedule",
                passed=wired,
                score=1.0 if wired else (0.5 if parts else 0.0),
                details=f"Daemon tasks wired: {', '.join(parts) if parts else 'none'}",
                recommendation="" if wired else "Wire helix_prerender + helix_assemble in autonomous_daemon.py",
            )
        )
    except Exception as exc:
        results.append(
            HealthCheckResult(
                source=HealthSource.HELIX_NEWS,
                name="helix_daemon_schedule",
                passed=False,
                score=0.0,
                details=f"Schedule check error: {exc}",
            )
        )

    return results


# ═══════════════════════════════════════════════════════════════
#  Dashboard Tile Builder
# ═══════════════════════════════════════════════════════════════


def _build_tiles(
    overall_score: float,
    health_status: str,
    checks: list[HealthCheckResult],
    slo_statuses: list[SLOStatus],
    pillar_summary: dict[str, Any],
) -> list[DashboardTile]:
    """Build dashboard tiles from current health data."""
    tiles: list[DashboardTile] = []

    # Overall health tile
    if overall_score >= 0.9:
        color = "green"
    elif overall_score >= 0.7:
        color = "yellow"
    else:
        color = "red"

    tiles.append(
        DashboardTile(
            tile_type="health",
            title="System Health",
            value=round(overall_score * 100, 1),
            status=color,
            subtitle=health_status,
        )
    )

    # Checks pass rate tile
    passed = sum(1 for c in checks if c.passed)
    total = len(checks)
    tiles.append(
        DashboardTile(
            tile_type="health",
            title="Checks Passed",
            value=f"{passed}/{total}",
            status="green" if passed == total else ("yellow" if passed > total * 0.7 else "red"),
            subtitle=f"{(passed / total * 100):.0f}% pass rate" if total > 0 else "No checks",
        )
    )

    # SLO tiles
    for slo_status in slo_statuses:
        tiles.append(
            DashboardTile(
                tile_type="slo",
                title=slo_status.slo.name.replace("_", " ").title(),
                value=f"{slo_status.current_value:.0%}",
                status="green"
                if not slo_status.in_violation
                else ("red" if slo_status.budget_remaining < 0.3 else "yellow"),
                subtitle=f"Target: {slo_status.slo.target:.0%} | Budget: {slo_status.budget_remaining:.0%}",
            )
        )

    # Pillar status tiles
    for pid, info in pillar_summary.get("pillars", {}).items():
        status = info.get("status", "offline")
        tiles.append(
            DashboardTile(
                tile_type="pillar",
                title=info.get("name", pid),
                value=status.upper(),
                status="green"
                if status == "online"
                else ("yellow" if status in ("degraded", "bootstrapping") else "red"),
                subtitle=f"{info.get('role', '')} — {info.get('capabilities', 0)} caps",
            )
        )

    # Source breakdown tiles
    source_scores: dict[str, list[float]] = {}
    for check in checks:
        source_scores.setdefault(check.source.value, []).append(check.score)
    for source, scores in source_scores.items():
        avg = sum(scores) / len(scores) if scores else 0.0
        tiles.append(
            DashboardTile(
                tile_type="health",
                title=source.replace("_", " ").title(),
                value=f"{avg:.0%}",
                status="green" if avg >= 0.9 else ("yellow" if avg >= 0.7 else "red"),
                subtitle=f"{len(scores)} checks",
            )
        )

    # HELIX News tile
    helix_checks = [c for c in checks if c.name.startswith("helix_")]
    if helix_checks:
        helix_score = sum(c.score for c in helix_checks) / len(helix_checks)
        helix_passed = sum(1 for c in helix_checks if c.passed)
        tiles.append(
            DashboardTile(
                tile_type="health",
                title="HELIX News",
                value=f"{helix_passed}/{len(helix_checks)}",
                status="green" if helix_passed == len(helix_checks) else ("yellow" if helix_passed > 0 else "red"),
                subtitle=f"{helix_score:.0%} pipeline health",
            )
        )

    # Daily briefs tile
    brief_checks = [c for c in checks if c.name.startswith("brief_")]
    if brief_checks:
        brief_score = sum(c.score for c in brief_checks) / len(brief_checks)
        fresh_count = sum(1 for c in brief_checks if c.passed)
        tiles.append(
            DashboardTile(
                tile_type="health",
                title="Daily Briefs",
                value=f"{fresh_count}/{len(brief_checks)}",
                status="green" if fresh_count == len(brief_checks) else ("yellow" if fresh_count > 0 else "red"),
                subtitle=f"{brief_score:.0%} coverage",
            )
        )

    return tiles


# ═══════════════════════════════════════════════════════════════
#  Matrix Monitor Orchestrator — THE command surface
# ═══════════════════════════════════════════════════════════════


class MatrixMonitorOrchestrator:
    """NCC Matrix Monitor Command & Control.

    Single entry point that:
        1. Collects health data from all subsystems
        2. Evaluates SLOs against history
        3. Generates alerts on threshold violations
        4. Builds dashboard tiles
        5. Persists everything to the store

    Usage::

        monitor = MatrixMonitorOrchestrator()
        report = monitor.collect_all()
        print(report.health_status)
    """

    _instance: ClassVar[MatrixMonitorOrchestrator | None] = None

    def __init__(
        self,
        repo_root: Path | None = None,
        config: dict[str, Any] | None = None,
    ) -> None:
        self.repo_root = repo_root or _REPO_ROOT
        self._config = config or self._load_config()
        self.store = MatrixMonitorStore(
            log_dir=self.repo_root / "ncl_agency_runtime" / "logs",
        )
        self.slo_engine = SLOEngine(config=self._config)
        self.alert_router = AlertRouter()
        self._boot_time = time.time()
        self._cycle_count = 0

    @classmethod
    def get_instance(cls, **kwargs: Any) -> MatrixMonitorOrchestrator:
        if cls._instance is None:
            cls._instance = cls(**kwargs)
        return cls._instance

    @classmethod
    def reset(cls) -> None:
        cls._instance = None

    def _load_config(self) -> dict[str, Any]:
        """Load configuration from ncl_config.json."""
        config_path = self.repo_root / "ncl_config.json"
        if config_path.exists():
            try:
                return json.loads(config_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                pass
        return {}

    # ── Core Collection Cycle ─────────────────────────────────

    def collect_all(self) -> MatrixReport:
        """Run all health collectors and produce a unified MatrixReport.

        This is the primary entry point — call this to get the full
        system health picture.
        """
        self._cycle_count += 1
        LOG.info("Matrix Monitor collection cycle #%d starting", self._cycle_count)

        # 1. Collect from all sources
        all_checks: list[HealthCheckResult] = []

        system_checks = _collect_system_health(self.repo_root)
        all_checks.extend(system_checks)

        self_checks = _collect_self_check(self.repo_root)
        all_checks.extend(self_checks)

        gov_checks, pillar_summary = _collect_ncc_governance(self.repo_root)
        all_checks.extend(gov_checks)

        fpc_checks = _collect_fpc_health(self.repo_root)
        all_checks.extend(fpc_checks)

        brief_checks, self._brief_summary = _collect_daily_briefs(self.repo_root)
        all_checks.extend(brief_checks)

        autonomous_checks = _collect_autonomous_ops(self.repo_root)
        all_checks.extend(autonomous_checks)

        intelligence_checks = _collect_intelligence_health(self.repo_root)
        all_checks.extend(intelligence_checks)

        forecasting_checks = _collect_forecasting_health(self.repo_root)
        all_checks.extend(forecasting_checks)

        memory_checks = _collect_memory_health(self.repo_root)
        all_checks.extend(memory_checks)

        comms_checks = _collect_communication_health(self.repo_root)
        all_checks.extend(comms_checks)

        helix_checks = _collect_helix_news(self.repo_root)
        all_checks.extend(helix_checks)

        # 2. Calculate overall score
        if all_checks:
            overall_score = round(
                sum(c.score for c in all_checks) / len(all_checks),
                3,
            )
        else:
            overall_score = 0.0

        health_status = self._health_label(overall_score)
        passed_count = sum(1 for c in all_checks if c.passed)

        # 3. Build metrics for SLO evaluation
        total_pillars = pillar_summary.get("total_pillars", 0)
        online_pillars = pillar_summary.get("online", 0)

        current_metrics = {
            "overall_score": overall_score,
            "pillar_online_ratio": online_pillars / total_pillars if total_pillars > 0 else 0.0,
            "checks_pass_rate": passed_count / len(all_checks) if all_checks else 0.0,
        }

        # 4. Evaluate SLOs
        history = self.store.get_history(max_entries=200)
        slo_statuses = self.slo_engine.evaluate(current_metrics, history)
        slos_in_violation = sum(1 for s in slo_statuses if s.in_violation)

        # 5. Generate alerts
        new_alerts = self.alert_router.evaluate(all_checks, slo_statuses, overall_score)

        # 6. Build dashboard tiles
        tiles = _build_tiles(overall_score, health_status, all_checks, slo_statuses, pillar_summary)

        # 7. Assemble report
        report = MatrixReport(
            timestamp=datetime.now(UTC).isoformat(),
            overall_score=overall_score,
            health_status=health_status,
            checks=all_checks,
            checks_passed=passed_count,
            checks_total=len(all_checks),
            slo_statuses=slo_statuses,
            slos_in_violation=slos_in_violation,
            alerts=new_alerts,
            tiles=tiles,
            pillar_summary=pillar_summary,
            uptime_s=round(time.time() - self._boot_time, 1),
        )

        # 8. Persist
        self.store.save(report)

        LOG.info(
            "Matrix Monitor cycle #%d complete: score=%.2f status=%s checks=%d/%d slo_violations=%d alerts=%d",
            self._cycle_count,
            overall_score,
            health_status,
            passed_count,
            len(all_checks),
            slos_in_violation,
            len(new_alerts),
        )

        return report

    # ── Individual Collector Access ───────────────────────────

    def collect_system(self) -> list[HealthCheckResult]:
        """Run only system health checks."""
        return _collect_system_health(self.repo_root)

    def collect_self_check(self) -> list[HealthCheckResult]:
        """Run only self-check protocol."""
        return _collect_self_check(self.repo_root)

    def collect_governance(self) -> tuple[list[HealthCheckResult], dict[str, Any]]:
        """Run only NCC governance checks."""
        return _collect_ncc_governance(self.repo_root)

    def collect_fpc(self) -> list[HealthCheckResult]:
        """Run only FPC intelligence checks."""
        return _collect_fpc_health(self.repo_root)

    def collect_autonomous_ops(self) -> list[HealthCheckResult]:
        """Run only autonomous operations checks."""
        return _collect_autonomous_ops(self.repo_root)

    def collect_intelligence(self) -> list[HealthCheckResult]:
        """Run only intelligence engine checks."""
        return _collect_intelligence_health(self.repo_root)

    def collect_forecasting(self) -> list[HealthCheckResult]:
        """Run only forecasting subsystem checks."""
        return _collect_forecasting_health(self.repo_root)

    def collect_memory(self) -> list[HealthCheckResult]:
        """Run only memory subsystem checks."""
        return _collect_memory_health(self.repo_root)

    def collect_communication(self) -> list[HealthCheckResult]:
        """Run only communication layer checks."""
        return _collect_communication_health(self.repo_root)

    # ── Dashboard API ─────────────────────────────────────────

    def get_tiles(self) -> list[dict[str, Any]]:
        """Get current dashboard tiles from latest report."""
        latest = self.store.get_latest()
        if latest:
            return latest.get("tiles", [])
        return []

    def get_trend(self, metric: str = "score", days: int = 7) -> list[dict[str, Any]]:
        """Get trend data for a metric."""
        max_entries = days * 24  # assume at most hourly collection
        return self.store.get_trend(metric, max_entries=max_entries)

    # ── Alert Management ──────────────────────────────────────

    def get_active_alerts(self) -> list[dict[str, Any]]:
        """Get unacknowledged alerts."""
        return [a.to_dict() for a in self.alert_router.active_alerts]

    def acknowledge_alert(self, index: int) -> bool:
        """Acknowledge an alert by index."""
        return self.alert_router.acknowledge(index)

    # ── SLO Access ────────────────────────────────────────────

    def get_slo_definitions(self) -> list[dict[str, Any]]:
        """Get all SLO definitions."""
        return [s.to_dict() for s in self.slo_engine.slo_definitions]

    # ── Bus Integration ───────────────────────────────────────

    def publish_to_bus(self, report: MatrixReport) -> None:
        """Publish health report to the InterPillarBus for cross-pillar awareness."""
        try:
            from ncl_agency_runtime.runtime.inter_pillar_bus import (
                InterPillarBus,
                MessageType,
                PillarMessage,
                Priority,
            )
            from ncl_agency_runtime.runtime.pillar_registry import PillarID

            bus = InterPillarBus.get_instance()
            msg = PillarMessage(
                source=PillarID.NCC,
                target=PillarID.NCC,
                msg_type=MessageType.STATUS_REPORT,
                payload={
                    "report_type": "matrix_monitor",
                    "overall_score": report.overall_score,
                    "health_status": report.health_status,
                    "checks_passed": report.checks_passed,
                    "checks_total": report.checks_total,
                    "slos_in_violation": report.slos_in_violation,
                    "alerts_count": len(report.alerts),
                },
                priority=Priority.HIGH if report.overall_score < 0.5 else Priority.NORMAL,
            )

            # Sync dispatch — no async context required
            bus.dispatch_sync(msg)

            # Publish critical alerts as ALERT messages
            for alert in report.alerts:
                if alert.severity in (AlertSeverity.CRITICAL, AlertSeverity.ERROR):
                    alert_msg = PillarMessage(
                        source=PillarID.NCC,
                        target=PillarID.NCC,
                        msg_type=MessageType.ALERT,
                        payload=alert.to_dict(),
                        priority=Priority.CRITICAL if alert.severity == AlertSeverity.CRITICAL else Priority.HIGH,
                    )
                    bus.dispatch_sync(alert_msg)

        except Exception as exc:
            LOG.warning("Failed to publish to bus: %s", exc)

    # ── Utilities ─────────────────────────────────────────────

    @staticmethod
    def _health_label(score: float) -> str:
        if score >= 0.9:
            return "EXCELLENT"
        if score >= 0.7:
            return "GOOD"
        if score >= 0.5:
            return "FAIR"
        if score >= 0.3:
            return "DEGRADED"
        return "CRITICAL"

    @property
    def cycle_count(self) -> int:
        return self._cycle_count

    @property
    def uptime_s(self) -> float:
        return round(time.time() - self._boot_time, 1)


# ═══════════════════════════════════════════════════════════════
#  CLI Entry Point
# ═══════════════════════════════════════════════════════════════


def main() -> None:
    """Run Matrix Monitor from command line."""
    import sys

    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] %(levelname)-8s %(name)s  %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
    )

    monitor = MatrixMonitorOrchestrator()
    report = monitor.collect_all()

    # Publish to bus
    monitor.publish_to_bus(report)

    # Print summary
    print(f"\n{'=' * 60}")
    print(f"  NCC MATRIX MONITOR — {report.health_status}")
    print(f"{'=' * 60}")
    print(f"  Overall Score : {report.overall_score:.1%}")
    print(f"  Checks Passed : {report.checks_passed}/{report.checks_total}")
    print(f"  SLO Violations: {report.slos_in_violation}")
    print(f"  Active Alerts : {len(report.alerts)}")
    print(f"  Uptime        : {report.uptime_s:.0f}s")
    print(f"{'=' * 60}")

    # Print tiles
    print("\n  DASHBOARD TILES")
    print(f"  {'-' * 56}")
    for tile in report.tiles:
        indicator = {"green": "[OK]", "yellow": "[!!]", "red": "[XX]", "grey": "[--]"}.get(tile.status, "[??]")
        print(f"  {indicator} {tile.title}: {tile.value} — {tile.subtitle}")

    # Print alerts
    if report.alerts:
        print(f"\n  ALERTS ({len(report.alerts)})")
        print(f"  {'-' * 56}")
        for alert in report.alerts:
            sev = alert.severity.value.upper()
            print(f"  [{sev}] {alert.title}: {alert.details}")

    # Print daily briefs
    brief_checks = [c for c in report.checks if c.name.startswith("brief_")]
    if brief_checks:
        print("\n  DAILY BRIEFS")
        print(f"  {'-' * 56}")
        for bc in brief_checks:
            indicator = "[OK]" if bc.passed else ("[!!]" if bc.score > 0 else "[XX]")
            print(f"  {indicator} {bc.details}")
            if bc.recommendation:
                print(f"        -> {bc.recommendation}")
        # Show paths to latest briefs
        brief_summary = getattr(monitor, "_brief_summary", {})
        for btype in ("az", "csuite"):
            info = brief_summary.get(btype, {})
            if info.get("md"):
                print(f"        MD:  {info['md']}")
            if info.get("pdf"):
                print(f"        PDF: {info['pdf']}")

    # Print SLOs
    print("\n  SLO STATUS")
    print(f"  {'-' * 56}")
    for slo_status in report.slo_statuses:
        indicator = "[OK]" if not slo_status.in_violation else "[XX]"
        print(
            f"  {indicator} {slo_status.slo.name}: "
            f"{slo_status.current_value:.1%} "
            f"(target: {slo_status.slo.target:.1%}, "
            f"budget: {slo_status.budget_remaining:.0%})"
        )

    print("\n  Report saved to: ncl_agency_runtime/logs/matrix_latest.json")
    print(f"{'=' * 60}\n")

    # Exit code: 0 if healthy, 1 if degraded/critical
    sys.exit(0 if report.overall_score >= 0.5 else 1)


if __name__ == "__main__":
    main()
